language: go

go:
  - 1.9.x

branches:
  only:
    - master

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get -y update
  - sudo apt-get -y install solc
  - wget https://developers.yubico.com/YubiHSM2/Releases/yubihsm2-sdk-1.0.1-ubuntu1404-amd64.tar.gz
  - mkdir $HOME/yubihsm2
  - tar -xzf yubihsm2-sdk-1.0.1-ubuntu1404-amd64.tar.gz -C $HOME/yubihsm2

script:
  - export CGO_LDFLAGS=-L$HOME/yubihsm2/lib/
  - export CGO_CFLAGS=-I$HOME/yubihsm2/include/
  - go test -v -tags yubihsm ./...
